spring:
  messages:
    basename: i18n.login
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.wilsonovo.springboot.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml